---
name: XML-Easy
version: 0.005
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: XML processing with a clean interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Params::Classify: 0
  parent: 0
  perl: 5.008
  strict: 0
  warnings: 0
build_requires:
  Encode: 0
  IO::File: 0
  Module::Build: 0
  Params::Classify: 0
  Scalar::Util: 0
  Test::More: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
recommends:
  Internals: 0
  XSLoader: 0
dynamic_config: 1
provides:
  XML::Easy:
    file: lib/XML/Easy.pm
    version: 0.005
  XML::Easy::Classify:
    file: lib/XML/Easy/Classify.pm
    version: 0.005
  XML::Easy::Content:
    file: lib/XML/Easy/Content.pm
    version: 0.005
  XML::Easy::Element:
    file: lib/XML/Easy/Element.pm
    version: 0.005
  XML::Easy::NodeBasics:
    file: lib/XML/Easy/NodeBasics.pm
    version: 0.005
  XML::Easy::Syntax:
    file: lib/XML/Easy/Syntax.pm
    version: 0.005
  XML::Easy::Text:
    file: lib/XML/Easy/Text.pm
    version: 0.005
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
